# Generated by Django 6.0 on 2025-12-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
