# Generated by Django 6.0 on 2026-01-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='counselingsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('in_person', 'In Person')], max_length=20),
        ),
    ]
